[gcp_service_account]
type = "service_account"
project_id = "lyrical-mason-444709-h7"
private_key_id = "f139438881fb0e35ad89af525e9131b2092a9c70"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC27mLx4NL0gkIl
...
-----END PRIVATE KEY-----"""
client_email = "trainer-evaluation@lyrical-mason-444709-h7.iam.gserviceaccount.com"
client_id = "112332836240830838888"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/trainer-evaluation%40lyrical-mason-444709-h7.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
